
-- Generated by ORDS REST Data Services 19.4.1.r0572045
-- Schema: SCHALTSTELLE  Date: Mo Jun 01 01:21:50 2020 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'SCHALTSTELLE',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'schaltstelle',
      p_auto_rest_auth      => TRUE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'proposal',
      p_base_path      => '/proposal/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'proposal',
      p_pattern        => 'isPitchNeeded',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'proposal',
      p_pattern        => 'isPitchNeeded',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'begin
    update antrag set is_pitch_needed = :is_pitch_needed
    where id = :id;
    :status := 200;
exception
    when others then
        :status := 400;
end;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'proposal',
      p_pattern            => 'isPitchNeeded',
      p_method             => 'POST',
      p_name               => 'id',
      p_bind_variable_name => 'id',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'proposal',
      p_pattern            => 'isPitchNeeded',
      p_method             => 'POST',
      p_name               => 'is_pitch_needed',
      p_bind_variable_name => 'is_pitch_needed',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'proposal',
      p_pattern            => 'isPitchNeeded',
      p_method             => 'POST',
      p_name               => 'status',
      p_bind_variable_name => 'status',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'proposal',
      p_pattern        => 'sendMail',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'proposal',
      p_pattern        => 'sendMail',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    sent_status boolean := false;
    responseStatus NUMBER;
BEGIN
    APEX_MAIL.SEND(
        p_to        => :toEmail ,
        p_from      => :fromEmail ,
        p_cc        => :ccEmail ,
        p_subj      => :emailSubject ,
        p_body      => :emailBody ,
        p_body_html => :emailBodyHTML );
    sent_status := true; 
    responseStatus := 200;
    COMMIT;
END;
');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'proposal',
      p_pattern            => 'sendMail',
      p_method             => 'POST',
      p_name               => 'ccEmail',
      p_bind_variable_name => 'ccEmail',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'proposal',
      p_pattern            => 'sendMail',
      p_method             => 'POST',
      p_name               => 'emailBody',
      p_bind_variable_name => 'emailBody',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'proposal',
      p_pattern            => 'sendMail',
      p_method             => 'POST',
      p_name               => 'emailBodyHTML',
      p_bind_variable_name => 'emailBodyHTML',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'proposal',
      p_pattern            => 'sendMail',
      p_method             => 'POST',
      p_name               => 'emailSubject',
      p_bind_variable_name => 'emailSubject',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'proposal',
      p_pattern            => 'sendMail',
      p_method             => 'POST',
      p_name               => 'fromEmail',
      p_bind_variable_name => 'fromEmail',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'proposal',
      p_pattern            => 'sendMail',
      p_method             => 'POST',
      p_name               => 'toEmail',
      p_bind_variable_name => 'toEmail',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'proposal',
      p_pattern        => 'setProposalStatus',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'proposal',
      p_pattern        => 'setProposalStatus',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'begin
    update antrag set proposal_status = :proposal_status
    where id = :id;
    :status := 200;
    :location := :id;
exception
    when others then
        :status := 400;
end;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'proposal',
      p_pattern            => 'setProposalStatus',
      p_method             => 'POST',
      p_name               => 'id',
      p_bind_variable_name => 'id',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'proposal',
      p_pattern            => 'setProposalStatus',
      p_method             => 'POST',
      p_name               => 'location',
      p_bind_variable_name => 'location',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'proposal',
      p_pattern            => 'setProposalStatus',
      p_method             => 'POST',
      p_name               => 'proposal_status',
      p_bind_variable_name => 'proposal_status',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'proposal',
      p_pattern            => 'setProposalStatus',
      p_method             => 'POST',
      p_name               => 'status',
      p_bind_variable_name => 'status',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'proposal',
      p_pattern        => 'setVetoStartDate',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'proposal',
      p_pattern        => 'setVetoStartDate',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'begin
    update antrag set veto_start_date = :veto_start_date
    where id = :id;
    :status := 200;
exception
    when others then
        :status := 400;
end;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'proposal',
      p_pattern            => 'setVetoStartDate',
      p_method             => 'POST',
      p_name               => 'id',
      p_bind_variable_name => 'id',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'proposal',
      p_pattern            => 'setVetoStartDate',
      p_method             => 'POST',
      p_name               => 'status',
      p_bind_variable_name => 'status',
      p_source_type        => 'RESPONSE',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'proposal',
      p_pattern            => 'setVetoStartDate',
      p_method             => 'POST',
      p_name               => 'veto_start_date',
      p_bind_variable_name => 'veto_start_date',
      p_source_type        => 'HEADER',
      p_param_type         => 'TIMESTAMP',
      p_access_method      => 'IN',
      p_comments           => NULL);

    
        
COMMIT;

END;